### ISSUE TITLE
Change from 12.10.7 to 12.13.37 causes cryptic stack trace

### ISSUE THREAD

**Issue by eric-tucker** [chef-cookbooks/compat_resource#88]
### Cookbook version
12.13.37

### Chef-client version
12.5.1

### Platform Details
Amazon Linux 
Linux ip-10-61-80-11 4.4.15-25.57.amzn1.x86_64 #1 SMP Wed Jul 27 22:37:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Scenario:
Running chef-client (zero mode)

### Steps to Reproduce:
Basically my run list is java and the Jenkins community cookbook plus a few other basic recipes to install docker using the community cookbook calling the resources from that cookbook.

### Expected Result:
chef-client to run without errors like it does in 12.10.7 compat_resource.  :)

### Actual Result:
```
Compiling Cookbooks...
/etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:643: warning: already initialized constant Chef::RunContext::ChildRunContext::CHILD_STATE
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/run_context.rb:601: warning: previous definition of CHILD_STATE was here

================================================================================
Recipe Compile Error in /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/libraries/autoload.rb
================================================================================

RuntimeError
------------
ERROR: not all methods of RunContext accounted for in ChildRunContext! All methods must be marked as child methods with CHILD_STATE or delegated to the parent_run_context. Missing cheffish, chef_provisioning, chef_metal.

Cookbook Trace:
---------------
  /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:672:in `<class:ChildRunContext>'
  /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:603:in `<class:RunContext>'
  /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:43:in `<class:Chef>'
  /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:39:in `<top (required)>'
  /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches.rb:15:in `<top (required)>'
  /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/resource.rb:1:in `<top (required)>'
  /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/compat_resource.rb:7:in `<top (required)>'
  /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/libraries/autoload.rb:16:in `<top (required)>'

Relevant File Content:
----------------------
/etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:

665:          resource_collection
666:          resource_collection=
667:        }.map { |x| x.to_sym }
668:  
669:        # Verify that we didn't miss any methods
670:        missing_methods = superclass.instance_methods(false) - instance_methods(false) - CHILD_STATE
671:        if !missing_methods.empty?
672>>         raise "ERROR: not all methods of RunContext accounted for in ChildRunContext! All methods must be marked as child methods with CHILD_STATE or delegated to the parent_run_context. Missing #{missing_methods.join(", ")}."
673:        end
674:      end
675:    end
676:  end
677:  end
678:  


Running handlers:
[2016-08-25T12:07:54+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-08-25T12:07:54+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 05 seconds
[2016-08-25T12:07:54+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2016-08-25T12:07:54+00:00] ERROR: ERROR: not all methods of RunContext accounted for in ChildRunContext! All methods must be marked as child methods with CHILD_STATE or delegated to the parent_run_context. Missing cheffish, chef_provisioning, chef_metal.
[2016-08-25T12:07:54+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Maybe this error means something to you folks, but this is useless to me.

Downgrading to 12.10.7 makes this go away.

**Comment by taupen** [comment]
I'm having the same issue with the 12.13.37 tag. 12.10.7 works.

10:53:28.580        ================================================================================
10:53:28.581        Recipe Compile Error in /tmp/kitchen/cookbooks/compat_resource/libraries/autoload.rb
10:53:28.581        ================================================================================
10:53:28.582        
10:53:28.582        RuntimeError
10:53:28.583        ------------
10:53:28.583        ERROR: not all methods of RunContext accounted for in ChildRunContext! All methods must be marked as child methods with CHILD_STATE or delegated to the parent_run_context. Missing cheffish.
10:53:28.584        
10:53:28.584        Cookbook Trace:
10:53:28.585        ---------------
10:53:28.585          /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:672:in `<class:ChildRunContext>'
10:53:28.586          /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:603:in `<class:RunContext>'
10:53:28.595          /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:43:in `<class:Chef>'
10:53:28.596          /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:39:in `<top (required)>'
10:53:28.596          /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches.rb:15:in `<top (required)>'
10:53:28.597          /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/resource.rb:1:in `<top (required)>'
10:53:28.597          /tmp/kitchen/cookbooks/compat_resource/files/lib/compat_resource.rb:7:in `<top (required)>'
10:53:28.598          /tmp/kitchen/cookbooks/compat_resource/libraries/autoload.rb:16:in `<top (required)>'
10:53:28.598        
10:53:28.599        Relevant File Content:
10:53:28.599        ----------------------
10:53:28.600        /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:
10:53:28.600        
10:53:28.601        665:          resource_collection
10:53:28.601        666:          resource_collection=
10:53:28.602        667:        }.map { |x| x.to_sym }
10:53:28.602        668:  
10:53:28.603        669:        # Verify that we didn't miss any methods
10:53:28.603        670:        missing_methods = superclass.instance_methods(false) - instance_methods(false) - CHILD_STATE
10:53:28.604        671:        if !missing_methods.empty?
10:53:28.605        672>>         raise "ERROR: not all methods of RunContext accounted for in ChildRunContext! All methods must be marked as child methods with CHILD_STATE or delegated to the parent_run_context. Missing #{missing_methods.join(", ")}."
10:53:28.605        673:        end
10:53:28.606        674:      end
10:53:28.606        675:    end
10:53:28.607        676:  end
10:53:28.607        677:  end
10:53:28.608        678:  
10:53:28.608        
10:53:28.609        
10:53:28.609        Running handlers:
10:53:28.610        [2016-08-25T11:53:27+01:00] ERROR: Running exception handlers
10:53:28.610        Running handlers complete
10:53:28.611        [2016-08-25T11:53:27+01:00] ERROR: Exception handlers complete
10:53:28.611        Chef Client failed. 0 resources updated in 01 seconds
10:53:28.612        [2016-08-25T11:53:27+01:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
10:53:28.612        [2016-08-25T11:53:27+01:00] ERROR: ERROR: not all methods of RunContext accounted for in ChildRunContext! All methods must be marked as child methods with CHILD_STATE or delegated to the parent_run_context. Missing cheffish.
10:53:28.613        [2016-08-25T11:53:27+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by max06** [comment]
Confirmed on 300+ Ubuntu Servers, Chef-Client 12.5.1. Downgrading fixes this.

**Comment by thommay** [comment]
Should be fixed in compat_resource 12.13.38.

**Comment by bclow-invoca** [comment]
Nope. Still borked. At least for Chef 12.11.18.

**Comment by thommay** [comment]
@bclow-invoca the same exact error?

**Comment by bclow-invoca** [comment]
Yes. It appears to be. It is failing in our chefspec testing on any cookbook that includes directly or indirectly compat_resource. It will fail initially with the same error:

```
/private/var/folders/wc/nhj12sj108q8yfnzj4rbkmbr0000gp/T/d20160825-98896-6oiuqg/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:643: warning: already initialized constant Chef::RunContext::ChildRunContext::CHILD_STATE
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/run_context.rb:661: warning: previous definition of CHILD_STATE was here
```

Then subsequent tests will fail with runtime errors:

```
Already loaded CompatResource from files/lib/compat_resource/gemspec.rb. Cannot load a second time from /private/var/folders/wc/nhj12sj108q8yfnzj4rbkmbr0000gp/T/chefspec20160825-98896-ziuvimfile_cache_path/cookbooks/compat_resource/files/lib/compat_resource/gemspec.rb
```

**Comment by thommay** [comment]
@bclow-invoca that's a completely different problem, i'm afraid. Please open a new bug.

**Comment by bclow-invoca** [comment]
ACK

**Comment by lamont-granquist** [comment]
should be fixed by #94

**Comment by shortdudey123** [comment]
Still seeing it with `12.13.38` but looks like `12.14.0` works
